### ISSUE TITLE
Multiple Hosts

### ISSUE THREAD

**Issue by adamlc** [Clever/thrift-pool#24]
Just an idea, it would be great to be able to specify multiple hosts, so we could pool connections across multiple hosts :)

**Comment by mohit** [comment]
@adamlc we are currently not investing resources into evolving our thrift ecosystem (see [Wag](https://github.com/Clever/wag) and therefore don't think we will be working on any new features on this repository. 

I would encourage you to submit a PR and I'm sure we can merge it into the repo :)
